### ISSUE TITLE
Feature Request: Add Option for Date

### ISSUE THREAD

**Issue by johnallen3d** [somdoron/spacebar#1]
The one thing that I've always missed while using the bar from `yabai` is having the current date visible (apparently  I have a hard time remembering the date).

**Comment by somdoron** [comment]
Do you think it should be part of the time or separate block?

If part of the time, it can be a format string provided at configuration

**Comment by johnallen3d** [comment]
As part of time makes sense to me. Presumably using the format string allows others to opt-in/out as they desire?

**Comment by nwaywood** [comment]
I agree, as part of the time to make it a modifiable through configuration which be great.

I have made this widget with Ubersicht to match the stying of the default bar, and with a configurable string it would be easy to replicate

![image](https://user-images.githubusercontent.com/3773641/77865165-afd78300-7278-11ea-8585-a4c7b459d801.png)

**Comment by somdoron** [comment]
Done, check out https://github.com/somdoron/spacebar/commit/9dc81e4bf911ab247f041e3cd01887a4b0341302

I also released a version.

In order to make the bar modular, we need some refactoring, it is mostly hard-coded now (like the length of the underline under the  clock)

**Comment by johnallen3d** [comment]
💥 Thanks again @somdoron!

<img width="261" alt="Monosnap 2020-03-30 08-53-54" src="https://user-images.githubusercontent.com/184915/77914541-13a38100-7264-11ea-9c5d-49ce5a0e237a.png">
