### ISSUE TITLE
[Feature Request] Transparent status bar

### ISSUE THREAD

**Issue by nicholaswong31415** [somdoron/spacebar#19]
Would it be possible to have an option to be able to set the opacity of the status bar in the spacebarrc config file? Something like:

`spacebar -m config bar_opacity 0.9`

I managed to manually set the opacity in the bar_refresh function in bar.c by using CGContextSetAlpha like so:

![image](https://user-images.githubusercontent.com/42924212/86515281-1d3c1680-be5b-11ea-9f4f-f18b76cc9635.png)

It does work, however it requires the status bar to refresh itself first so upon first loading it will not set the opacity, but this was more of a trial to see if it worked.

I'm not very familiar with C, so I'm not too sure how the options are read in from the spacebarrc file and used within the code but hopefully this could be something not too hard to implement (I like having my windows in yabai slightly transparent so if the status bar could also match that then that would be really nice).

**Comment by nicholaswong31415** [comment]
It might have been a bit hard to see where I was using CGContextSetAlpha - it's in line 221 of my screenshot.

**Comment by koekeishiya** [comment]
The first two nibbles in the (existing) color values control transparency. E.g: 0x40458588

**Comment by nicholaswong31415** [comment]
Ah thanks very much! That helps a lot haha

**Comment by fenneltheloon** [comment]
I've set the alpha value for the background color to 0 in my config (attached), but the background color is still the default grey. Changing the other bytes for RGB seems to work as intended. This issue persists after restarting spacebar as well as the full system. Help appreciated!

[spacebarrc.txt](https://github.com/cmacrae/spacebar/files/14270621/spacebarrc.txt)
