### ISSUE TITLE
Does not recognize options in configuration file

### ISSUE THREAD

**Issue by fparrav** [somdoron/spacebar#8]
When I start via `brew services start spacebar` or manually it does not recognize the configuration file and loads the default configuration

```
➜ spacebar -c .config/spacebar/spacebarrc 
unknown command 'text_font' for domain 'config'
unknown command 'icon_font' for domain 'config'
unknown command 'background_color' for domain 'config'
unknown command 'foreground_color' for domain 'config'
unknown command 'space_icon_strip' for domain 'config'
unknown command 'power_icon_strip' for domain 'config'
unknown command 'space_icon' for domain 'config'
unknown command 'clock_icon' for domain 'config'
unknown command 'clock_format' for domain 'config'
spacebar configuration loaded..
```

The file has the following permissions :
```
➜ ls -ltr .config/spacebar/spacebarrc 
-rwxr-xr-x  1 kaos  staff  521 Apr 25 01:27 .config/spacebar/spacebarrc
```

**Comment by Eyjafjallajokull** [comment]
This is because example configuration includes changes that are not released in the brew package. You need to uninstall spacebar and install it with `--HEAD` and then sign it. https://github.com/somdoron/spacebar/issues/6

**Comment by fparrav** [comment]
Thanks, this solved my problem!

**Comment by SmithJson** [comment]
> This is because example configuration and readme include changes that are not released in the brew package. You need to uninstall spacebar and install it with `--HEAD` and then sign it. #6

Thanks, I solved this problem by your method
